#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: mx-activedirectory
# REQUIRE: mx-samba mx-kinit
# BEFORE: winbindd

. /etc/rc.metanas

: ${NSS_LDAP_CONF:="/usr/local/etc/nss_ldap.conf"}

generate_nss_ldap_conf()
{
	local IFS="|"
	local nssconf="${NSS_LDAP_CONF}"

	dcname=$(AD_get dcname)
	domainname=$(AD_get domainname)
	adminname=$(AD_get adminname)
	adminpw=$(AD_get adminpw)

	base=$(echo "${domainname}" | awk '{
		n = split($0, parts, ".");
		if (n > 0) {
			base = sprintf("dc=%s", parts[1]);
			for (i=2;i <= n;i++) {
				base = sprintf("%s,dc=%s", base, parts[i]);
			}
			printf("%s", base);
		}
	}')

	[ -z "${dcname}" -o -z "${base}" ] && return 1 

	cat > "${nssconf}" <<-EOF
	host ${dcname}
	base ${base}
	uri ldap://${dcname}/
	binddn ${adminname}@${domainname}
	bindpw ${adminpw}
	scope sub
	ssl no
	nss_base_passwd ${base}?sub
	nss_base_shadow ${base}?sub
	nss_base_group ${base}?sub? &(objectCategory=group)(gidnumber=*)
	nss_map_objectclass posixAccount user
	nss_map_objectclass shadowAccount user
	nss_map_objectclass posixGroup group
	nss_map_attribute gecos cn
	nss_map_attribute homeDirectory unixHomeDirectory
	nss_map_attribute uniqueMember member
EOF
	ln -s ${nssconf} "$(dirname ${nssconf})/ldap.conf" 2>/dev/null

	return 0
}


get_trusted()
{
	${METANAS_SQLITE_CMD} ${METANAS_CONFIG} "
	SELECT
		ad_allow_trusted_doms

	FROM
		services_activedirectory

	ORDER BY
		-services_activedirectory.id

	LIMIT 1;
	"
}

get_workgroup()
{
	${METANAS_SQLITE_CMD} ${METANAS_CONFIG} "
	SELECT
		ad_workgroup

	FROM
		services_activedirectory

	ORDER BY
		-services_activedirectory.id

	LIMIT 1;
	"
}

get_cifs_homedir()
{
	${METANAS_SQLITE_CMD} ${METANAS_CONFIG} "
	SELECT
		cifs_srv_homedir

	FROM
		services_cifs

	ORDER BY
		-services_cifs.id

	LIMIT 1;
	"
}


setup_homedirs()
{
	local trusted=$(get_trusted)
	local cifs_home="$(get_cifs_homedir)"

	if [ -n "${cifs_home}" ]
	then
		ln -sfh "$cifs_home" "/var/home"

		if [ "${trusted}" = "1" ]
		then
			local partitions="$(AD_query_partitions)"
			for p in ${partitions}
			do
				mkdir -p "/var/home/${p}"
			done

		else
			local workgroup=$(get_workgroup)
			mkdir -p "/var/home/${workgroup}"
		fi

	elif [ ! -d "/var/home" ]
	then
		mkdir /var/home
	fi
}

activedirectory_start()
{
	if srv_enabled activedirectory
	then
		AD_init
		if ! AD_join_domain; then
			return 1
		fi

		#generate_nss_ldap_conf

		setup_homedirs
		create_cache_filesystem
		mkdir -p ${METANAS_CACHEDIR}/.samba
	fi
	
	return 0
}

activedirectory_status()
{
	AD_init
	AD_status_domain >/dev/null
}

activedirectory_stop()
{
	AD_init

        /usr/local/www/metanasUI/tools/cachetool.py expire
	AD_leave_domain
}


name="mx-activedirectory"
start_cmd='activedirectory_start'
status_cmd='activedirectory_status'
stop_cmd='activedirectory_stop'
            
load_rc_config $name
run_rc_command "$1"
