#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: mx-motd
# REQUIRE: FILESYSTEMS
# BEFORE: motd

. /etc/rc.subr

generate_motd()
{
	cp /conf/base/etc/motd /etc/motd
	${METANAS_SQLITE_CMD} ${METANAS_CONFIG} "SELECT adv_motd FROM system_advanced ORDER BY id DESC LIMIT 1" >> /etc/motd
}

name="mx-motd"
start_cmd='generate_motd'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
