#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: mx-syncdisks
# REQUIRE: FILESYSTEMS

. /etc/rc.subr

syncdisks()
{
    /usr/local/bin/python /usr/local/www/metanasUI/tools/sync_disks.py
}

name="mx-syncdisks"
start_cmd='syncdisks'
stop_cmd=''

load_rc_config $name
run_rc_command "$1"
